services:
  - type: web
    name: email-agent-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your other environment variables here
    # - key: FIREBASE_PROJECT_ID
    #   value: your_project_id
    # - key: GOOGLE_CLIENT_ID
    #   value: your_google_client_id
    # etc...
